spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: public

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true


aws:
  region: test
  credentials:
    access-key: test
    secret-key: test
  bucket:
    image: test

internal:
  playground:
    url: test
    token: test
  crew:
    url: test

jwt:
  access: test
  refresh: test

official:
  apikey: test
